version: '3.4'

services:
  flaskrestful:
    image: flaskrestful:1.0.0
    container_name: flaskrestful
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app/flask_restful
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    ports:
      - 5002:5002
